apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-v1
  labels:
    app: demoapp
spec:
  replicas: 3
  strategy: {}
  selector:
    matchLabels:
      app: demoapp
      version: v1
  template:
    metadata:
      labels:
        app: demoapp
        version: v1
    spec:
      containers:
      - name: demoapp
        image: dmitriysh/demoapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USER
          value: "admin"
        - name: MONGO_PASSWORD
          value: "password"
        - name: MONGO_DB_NAME
          value: "test"
        - name: MONGO_AUTH_SOURCE
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
spec:
  type: NodePort
  selector:
    app: demoapp
    version: v1
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001